name: Sync GitHub and Jira release

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get version from package.json
        id: get-version
        run: echo ::set-output name=VERSION::$(node -p "require('./package.json').version")

      - name: Create Jira Release
        uses: GeoWerkstatt/create-jira-release@v1
        with:
          jira-project-key: "ANY"
          jira-automation-webhook: ${{ secrets.JIRA_AUTOMATION_WEBHOOK }}
          build-version: v${{ steps.get-version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
